CUDA_VISIBLE_DEVICES=0 python main.py --dataset cifar100 \
    --train_org_dir /datasets/cifar100/train \
    --train_aug_dir /diffuseMix/our_result/ \
    --test_dir /datasets/cifar100/test \
    --root_dir output/ours \
    --labels_per_class 500 \
    --arch preactresnet18 \
    --learning_rate 0.1 \
    --momentum 0.9 \
    --decay 0.0001 \
    --epochs 300 \
    --schedule 100 200 \
    --gammas 0.1 0.1 \
    --train vanilla \
    --use_wandb True \
    --wandb_project ours